SpiNNakerManchester/DataSpecification

data_specification/data_specification_executor_functions.py, setup.py
This speeds up array writing by about 15x - Reduces time taken to execute dataspec in my example from 1 minute to about 4s - SEEMS to work, but testing would obviously be beneficial
=> Optimised array writing

data_specification/data_specification_generator.py
This helps to measure the total SDRAM usage per chip
=> Added the ability to get a list of reserved region sizes

doc/doc_requirements.txt, doc/source/conf.py
Fix to docs conf.py to and doc_requirements to get master to build
No code changes not even docstrings
=> Read me fix

data_specification/__init__.py, data_specification/data_specification_executor.py, data_specification/data_specification_generator.py, data_specification/enums/__init__.py, data_specification/utility_calls.py, integration_tests/test_writing_file_then_reading_from_same_file.py, unittests/test_data_spec_executor.py, unittests/test_data_spec_executor_functions.py, unittests/test_data_spec_generator.py, unittests/test_enums.py, unittests/test_file_data_reader.py, unittests/test_file_data_writer.py, unittests/test_memory_region_collection.py
This is about shortening the sometimes over-long full names of classes.
=> Shorten names

data_specification/enums/data_type.py, unittests/test_enums.py
=> Fix S1615 min and max

data_specification/data_specification_executor.py
Wild tracebacks are a problem; let's crush them where possible!
=> Tracebacks should be done through the logger as much as possible

data_specification/abstract_executor_functions.py, data_specification/data_specification_executor_functions.py
This branch substantially simplifies the DSG core, mostly by factoring out functionality so that range and type-range checks are done in exactly the same (correct!) way everywhere.
=> A partial refactor of the DSE functions

data_specification/__init__.py, data_specification/abstract_executor_functions.py, data_specification/constants.py, data_specification/data_specification_executor.py, data_specification/data_specification_executor_functions.py, data_specification/data_specification_generator.py, data_specification/memory_region.py, data_specification/memory_region_collection.py, data_specification/utility_calls.py
=> Various small documentation fixes

data_specification/data_specification_executor_functions.py, data_specification/memory_region.py, unittests/test_data_spec_executor.py, unittests/test_memory_region_collection.py
Make pointers consistent again!
=> Pointer consistency

.travis.yml, data_specification/data_specification_generator.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
=> Enable testing with Python 3.7

setup.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
=> Depriaction Warnings

data_specification/utility_calls.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/372
All comments not very specific to DataSpecification code will be made there.
I suggest merging all relataed PRs at the same time.
=> Extractor2

unittests/test_data_spec_generator.py
Although this doesn't always happen, I have seen it cause issues, so here is the fix
=> Fix test (order should not be important)

setup.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102
=> fixed incorrect import from collections.abc

data_specification/data_specification_generator.py, data_specification/enums/data_type.py
Arranges for conversions to values to be pushed to the machine to all be done in one place and range-checked at that place.
=> One conversion site

data_specification/data_specification_generator.py, data_specification/enums/data_type.py
stuff to allow roberts ear to work correctly within pynn without hacks.
also adds support for static projections and will include selective recording. needs to be considered carefully for plastic projections.
needs prs:
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/241
https://github.com/SpiNNakerManchester/sPyNNaker/pull/682
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/459
https://github.com/SpiNNakerManchester/PACMAN/pull/236
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/115
https://github.com/SpiNNakerManchester/DataSpecification/pull/69
https://github.com/SpiNNakerManchester/SpiNNUtils/pull/97
https://github.com/SpiNNakerManchester/SupportScripts/pull/18
https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/36 …
=> Ear bit fields cleaned

.travis.yml, setup.py
Also run each version with best choice of Ubuntu distribution
=> Add testing with Python 3.8

.travis.yml, README.md, data_specification/data_specification_executor.py, data_specification/data_specification_executor_functions.py, data_specification/data_specification_generator.py, data_specification/utility_calls.py, doc/doc_requirements.txt, doc/source/conf.py, pypi_to_import, requirements.txt, setup.py, unittests/test_data_spec_executor.py, unittests/test_data_spec_generator.py, unittests/test_version.py
Purging the use of SpiNNStorageHandlers; the value of that repo is now zero.
See https://github.com/SpiNNakerManchester/SpiNNMan/pull/221
=> No more storage handlers

.github/workflows/python_actions.yml, README.md, data_specification/data_specification_executor.py, data_specification/data_specification_generator.py, data_specification/exceptions.py, data_specification/spi/abstract_executor_functions.py, doc/doc_requirements.txt, doc/source/conf.py, doc/source/index.rst, pypi_to_import, requirements-test.txt, requirements.txt, setup.py
PyPI and pip are forcing the issue; we can't keep going much longer.
SpiNNakerManchester/SpiNNUtils#132
=> Remove Python 2.7 support

requirements.txt, setup.py
found by https://github.com/SpiNNakerManchester/PACMAN/issues/417
=> SpinUtils imports numpy so no need to repeat complicated here

.pylintrc
Related to but independant of similar named prs
=> strickter pylint checks

data_specification/constants.py, data_specification/data_specification_executor.py, unittests/test_data_spec_executor.py
=> Reduce overhead

data_specification/__init__.py, data_specification/abstract_memory_region.py, data_specification/config_setup.py, data_specification/constants.py, data_specification/data_specification_executor.py, data_specification/data_specification_executor_functions.py, data_specification/data_specification_generator.py, data_specification/enums/arithemetic_operation.py, data_specification/enums/commands.py, data_specification/enums/condition.py, data_specification/enums/data_type.py, data_specification/enums/logic_operation.py, data_specification/enums/random_number_generator.py, data_specification/exceptions.py, data_specification/memory_region_collection.py, data_specification/memory_region_real.py, data_specification/memory_region_reference.py, data_specification/reference_context.py, data_specification/spi/abstract_executor_functions.py
This is a round of doc polishing and fixing of error messages and so on.
See SpiNNakerManchester/SpiNNUtils#223
See https://dataspecification.readthedocs.io/en/doc-polish/
=> Doc polish

.github/dependabot.yml, .github/workflows/publish.yml, .github/workflows/python_actions.yml
* Add explicit timeouts to github jobs
* Add a dependabot config to keep action versions fresh
=> Improve github integration
